version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-task-4
  adminer:
    image: adminer
    restart: always
    networks:
      - test-task-4
    ports:
      - "8085:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column
networks:
  test-task-4:
    driver: bridge
volumes:
  postgres-data: